# Default values for whatsmyip.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: nginx
  pullPolicy: IfNotPresent

container:
  main:
    enabled: true
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx/
      readOnly: true
    - mountPath: /var/log/nginx
      name: log
service:
  main:
    ports:
      http:
        port: 80

ingress:
  main:
    enabled: true
    ingressClassName: public
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      external-dns.alpha.kubernetes.io/exclude: 'true'
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: whatsmyip.wibrow.net
        paths:
          - path: /
            pathType: Prefix
    tls:
    - secretName: whatsmyip-tls
      hosts:
        - whatsmyip.wibrow.net



configmap:
  config:
    enabled: true
    data:
      nginx.conf: |
        user nginx;
        worker_processes  1;
        error_log  /var/log/nginx/error.log;
        events {
          worker_connections  10240;
        }
        http {
          log_format  main
                  'remote_addr:$remote_addr\t'
                  'time_local:$time_local\t'
                  'method:$request_method\t'
                  'uri:$request_uri\t'
                  'host:$host\t'
                  'status:$status\t'
                  'bytes_sent:$body_bytes_sent\t'
                  'referer:$http_referer\t'
                  'useragent:$http_user_agent\t'
                  'forwardedfor:$http_x_forwarded_for\t'
                  'request_time:$request_time';

          access_log	/var/log/nginx/access.log main;

          server {
              listen       80;

              server_name  whatsmyip.wibrow.net;

              keepalive_requests 0;
              location / {
                default_type text/plain;
                return 200 $http_x_forwarded_for\n;
              }
          }
        }
